"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const react_router_1 = require("@tanstack/react-router");
const AuthContext_1 = require("../context/AuthContext");
const Navbar = () => {
    const { user, logout } = (0, AuthContext_1.useAuth)();
    return ((0, jsx_runtime_1.jsx)("nav", { className: "bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md", children: (0, jsx_runtime_1.jsx)("div", { className: "container mx-auto px-4 py-1", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex justify-between items-center", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-6", children: [(0, jsx_runtime_1.jsx)(react_router_1.Link, { to: "/", className: "flex-shrink-0", children: (0, jsx_runtime_1.jsx)("img", { src: "/assets/logo.svg", alt: "Internet Records", className: "h-32 w-auto" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "hidden md:flex items-center space-x-4", children: [(0, jsx_runtime_1.jsx)(react_router_1.Link, { to: "/dashboard", className: "hover:text-indigo-200 transition", children: "Dashboard" }), (0, jsx_runtime_1.jsx)(react_router_1.Link, { to: "/upload", className: "hover:text-indigo-200 transition", children: "Upload" }), (0, jsx_runtime_1.jsx)(react_router_1.Link, { to: "/youtube-claim", className: "hover:text-indigo-200 transition", children: "YouTube Claim" }), (0, jsx_runtime_1.jsx)(react_router_1.Link, { to: "/youtube-oac", className: "hover:text-indigo-200 transition", children: "YouTube OAC" }), (0, jsx_runtime_1.jsx)(react_router_1.Link, { to: "/social-media-linking", className: "hover:text-indigo-200 transition", children: "Social Media" }), (0, jsx_runtime_1.jsx)(react_router_1.Link, { to: "/artist-profile-linking", className: "hover:text-indigo-200 transition", children: "Artist Profiles" }), user?.role === 'ADMIN' && ((0, jsx_runtime_1.jsx)(react_router_1.Link, { to: "/admin", className: "hover:text-indigo-200 transition", children: "Admin" }))] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-4", children: [(0, jsx_runtime_1.jsxs)("span", { className: "hidden md:inline text-sm", children: [user?.name, " (", user?.role, ")"] }), (0, jsx_runtime_1.jsx)("button", { onClick: logout, className: "bg-white text-indigo-600 px-4 py-1 rounded-md hover:bg-indigo-100 transition", children: "Logout" })] })] }) }) }));
};
exports.default = Navbar;
